server:
  context-path: /client
  port: 9999

security:
  oauth2:
    client:
      client-id: revo
      client-secret: revo
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
      scope: read
    resource:
      user-info-uri: http://localhost:8888/user
      token-info-uri: http://localhost:8080/oauth/check_token